### ISSUE TITLE
[버그] 처음으로/다시시작 버튼시 점수 초기화 안됨

### ISSUE THREAD

**Issue by janetchu05** [alswodl23/Project#10]
폼 로드 후 게임 진행하다가 처음으로 or 다시시작 버튼 클릭 - 정상적으로 게임 처음부터 진행은 되지만 점수 초기화 안되고 점수 올라가는 콤보도 초기화 안되는 것으로 보임

**Comment by alswodl23** [comment]
private void btnStart_Click(object sender, EventArgs e)
        {
            if (txtID.Text == "" || txtID.Text == "이름을 입력해주세요")
            {
                MessageBox.Show("닉네임을 입력해주세요(10자 이하)", "알림", MessageBoxButtons.OK, MessageBoxIcon.Exclamation);
            }
            else if (txtID.Text.Length > 10)
            {
                MessageBox.Show("닉네임은 10자 이하로 입력해주세요.", "알림", MessageBoxButtons.OK, MessageBoxIcon.Exclamation);
            }
            else
            {
                randomNumbers = new List<int>();

                id = txtID.Text;
                Score = 0;
                Score_Counrt = 0;
                string startTxt = "게임을 시작합니다. 준비 되셨죠?";
                string startTxtName = id + "님! " + startTxt;
                MessageBox.Show(startTxtName);

                if (rbtEasy.Checked == true)
                {
                    counter = 60;
                }
                else if(rbtNormal.Checked == true)
                {
                    counter = 45;
                }
                else if (rbtHard.Checked == true)
                {
                    counter = 30;
                }

                timer.Enabled = true;

                Start_Game();
            }
        }


시작 버튼에서 스코어와 콤보스코어 초기화 해주었습니다
