### ISSUE TITLE
[버그]GameK001, 002 텍스트 박스 문자에러

### ISSUE THREAD

**Issue by alswodl23** [alswodl23/Project#14]
숫자가 아닌 문자를 입력했을 경우 에러가 발생.

**Comment by Hellokjw** [comment]
<GameK001.cs 파일>
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Threading;
using System.Windows.Forms;

namespace SockSockGame
{ // 2번째 게임 프로젝트 만들기
	class GameK001
	{
		//Form1의 요소들에 접근하기 위해 객체 생성
		static Form1 form = Application.OpenForms.OfType<Form1>().FirstOrDefault();

		//랜덤번호 뽑기 위한 랜덤객체
		static Random rand = new Random();

		private int plus1, plus2, minus1, minus2, multi1, multi2, div1, div2, mod1, mod2;

		// 전역변수 선언
		// 1. Button 부분
		public Button btnStart = new Button();

		// 2. Label 부분
		public Label lblResult = new Label();
		public Label lblNotice = new Label();

		public Label plusLeftLabel = new Label();
		public Label plusLabel = new Label();
		public Label plusRightLabel = new Label();
		public Label lblEqual1 = new Label();

		public Label minusLeftLabel = new Label();
		public Label minusLabel = new Label();
		public Label minusRightLabel = new Label();
		public Label lblEqual2 = new Label();

		public Label multiLeftLabel = new Label();
		public Label multiLabel = new Label();
		public Label multiRightLabel = new Label();
		public Label lblEqual3 = new Label();

		public Label divLeftLabel = new Label();
		public Label divLabel = new Label();
		public Label divRightLabel = new Label();
		public Label lblEqual4 = new Label();

		// 3. TextBox 부분
		TextBox txtPlus = new TextBox();
		TextBox txtMinus = new TextBox();
		TextBox txtMulti = new TextBox();
		TextBox txtDivide = new TextBox();

		PictureBox ptbHeart1 = new PictureBox();
		PictureBox ptbHeart2 = new PictureBox();
		PictureBox ptbHeart3 = new PictureBox();

		internal void InitGameK001()
		{
			form.Visible_Game_Start();
			form.pnlMain.BackgroundImage = Properties.Resources.Beach01;

			// Label 속성:AutoSize, Font, Location, Name, Size, TabIndex, Text, ForeColor, BackColor			
			lblResult.AutoSize = true;
			lblResult.Font = new System.Drawing.Font("굴림", 18F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)129));
			lblResult.Location = new System.Drawing.Point(247, 520);
			lblResult.Name = "timeLabel";
			lblResult.Size = new System.Drawing.Size(0, 24);
			lblResult.TabIndex = 23;
			lblResult.Text = "";

			// A + B = ?
			plusLeftLabel.AutoSize = true;
			plusLeftLabel.Font = new System.Drawing.Font("굴림", 17F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)129));
			plusLeftLabel.Location = new System.Drawing.Point(247, 200);
			plusLeftLabel.Name = "plusLeftLabel";
			plusLeftLabel.Size = new System.Drawing.Size(28, 26);
			plusLeftLabel.TabIndex = 3;
			plusLeftLabel.Text = "?";

			plusLabel.AutoSize = true;
			plusLabel.Font = new System.Drawing.Font("굴림", 17F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)129));
			plusLabel.Location = new System.Drawing.Point(297, 200);
			plusLabel.Name = "plusLabel";
			plusLabel.Size = new System.Drawing.Size(28, 26);
			plusLabel.TabIndex = 4;
			plusLabel.Text = "+";

			plusRightLabel.AutoSize = true;
			plusRightLabel.Font = new System.Drawing.Font("굴림", 17F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)129));
			plusRightLabel.Location = new System.Drawing.Point(347, 200);
			plusRightLabel.Name = "plusRightLabel";
			plusRightLabel.Size = new System.Drawing.Size(28, 26);
			plusRightLabel.TabIndex = 5;
			plusRightLabel.Text = "?";

			lblEqual1.AutoSize = true;
			lblEqual1.Font = new System.Drawing.Font("굴림", 17F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)129));
			lblEqual1.Location = new System.Drawing.Point(397, 200);
			lblEqual1.Name = "lblEqual1";
			lblEqual1.Size = new System.Drawing.Size(28, 26);
			lblEqual1.TabIndex = 15;
			lblEqual1.Text = "=";

			// A - B = ?
			minusLeftLabel.AutoSize = true;
			minusLeftLabel.Font = new System.Drawing.Font("굴림", 17F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)129));
			minusLeftLabel.Location = new System.Drawing.Point(247, 240);
			minusLeftLabel.Name = "minusLeftLabel";
			minusLeftLabel.Size = new System.Drawing.Size(28, 26);
			minusLeftLabel.TabIndex = 6;
			minusLeftLabel.Text = "?";

			minusLabel.AutoSize = true;
			minusLabel.Font = new System.Drawing.Font("굴림", 17F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)129));
			minusLabel.Location = new System.Drawing.Point(297, 240);
			minusLabel.Name = "minusLabel";
			minusLabel.Size = new System.Drawing.Size(28, 26);
			minusLabel.TabIndex = 7;
			minusLabel.Text = "-";

			minusRightLabel.AutoSize = true;
			minusRightLabel.Font = new System.Drawing.Font("굴림", 17F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)129));
			minusRightLabel.Location = new System.Drawing.Point(347, 240);
			minusRightLabel.Name = "minusRightLabel";
			minusRightLabel.Size = new System.Drawing.Size(28, 26);
			minusRightLabel.TabIndex = 8;
			minusRightLabel.Text = "?";

			lblEqual2.AutoSize = true;
			lblEqual2.Font = new System.Drawing.Font("굴림", 17F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)129));
			lblEqual2.Location = new System.Drawing.Point(397, 240);
			lblEqual2.Name = "lblEqual2";
			lblEqual2.Size = new System.Drawing.Size(28, 27);
			lblEqual2.TabIndex = 16;
			lblEqual2.Text = "=";

			// A * B = ?
			multiLeftLabel.AutoSize = true;
			multiLeftLabel.Font = new System.Drawing.Font("굴림", 17F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)129));
			multiLeftLabel.Location = new System.Drawing.Point(247, 280);
			multiLeftLabel.Name = "multiLeftLabel";
			multiLeftLabel.Size = new System.Drawing.Size(28, 26);
			multiLeftLabel.TabIndex = 9;
			multiLeftLabel.Text = "?";

			multiLabel.AutoSize = true;
			multiLabel.Font = new System.Drawing.Font("굴림", 17F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)129));
			multiLabel.Location = new System.Drawing.Point(297, 280);
			multiLabel.Name = "multiLabel";
			multiLabel.Size = new System.Drawing.Size(28, 26);
			multiLabel.TabIndex = 10;
			multiLabel.Text = "×";

			multiRightLabel.AutoSize = true;
			multiRightLabel.Font = new System.Drawing.Font("굴림", 17F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)129));
			multiRightLabel.Location = new System.Drawing.Point(347, 280);
			multiRightLabel.Name = "multiRightLabel";
			multiRightLabel.Size = new System.Drawing.Size(28, 26);
			multiRightLabel.TabIndex = 11;
			multiRightLabel.Text = "?";

			lblEqual3.AutoSize = true;
			lblEqual3.Font = new System.Drawing.Font("굴림", 17F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)129));
			lblEqual3.Location = new System.Drawing.Point(397, 280);
			lblEqual3.Name = "lblEqual3";
			lblEqual3.Size = new System.Drawing.Size(28, 26);
			lblEqual3.TabIndex = 17;
			lblEqual3.Text = "=";

			// A / B = ?
			divLeftLabel.AutoSize = true;
			divLeftLabel.Font = new System.Drawing.Font("굴림", 17F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)129));
			divLeftLabel.Location = new System.Drawing.Point(247, 320);
			divLeftLabel.Name = "divLeftLabel";
			divLeftLabel.Size = new System.Drawing.Size(28, 26);
			divLeftLabel.TabIndex = 12;
			divLeftLabel.Text = "?";

			divLabel.AutoSize = true;
			divLabel.Font = new System.Drawing.Font("굴림", 17F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)129));
			divLabel.Location = new System.Drawing.Point(297, 320);
			divLabel.Name = "divLabel";
			divLabel.Size = new System.Drawing.Size(28, 26);
			divLabel.TabIndex = 13;
			divLabel.Text = "÷";

			divRightLabel.AutoSize = true;
			divRightLabel.Font = new System.Drawing.Font("굴림", 17F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)129));
			divRightLabel.Location = new System.Drawing.Point(347, 320);
			divRightLabel.Name = "divRightLabel";
			divRightLabel.Size = new System.Drawing.Size(28, 26);
			divRightLabel.TabIndex = 14;
			divRightLabel.Text = "?";

			lblEqual4.AutoSize = true;
			lblEqual4.Font = new System.Drawing.Font("굴림", 17F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)129));
			lblEqual4.Location = new System.Drawing.Point(397, 320);
			lblEqual4.Name = "lblEqual4";
			lblEqual4.Size = new System.Drawing.Size(28, 26);
			lblEqual4.TabIndex = 18;
			lblEqual4.Text = "=";

			lblNotice.AutoSize = true;
			lblNotice.Font = new System.Drawing.Font("굴림", 17F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)129));
			lblNotice.Location = new System.Drawing.Point(247, 360);
			lblNotice.Name = "lblNotice";
			lblNotice.Size = new System.Drawing.Size(408, 22);
			lblNotice.TabIndex = 34;
			lblNotice.Text = "나누기 문제는 정수로만 입력해주세요.";
			lblNotice.ForeColor = System.Drawing.Color.Black;
			lblNotice.Visible = true;

			// Button 속성: Location, Name, Size, TabIndex, Text, BackColor, Click
			btnStart.Location = new System.Drawing.Point(247, 400);
			btnStart.Name = "btnNext";
			btnStart.Font = new System.Drawing.Font("굴림", 15F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)129));
			btnStart.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
			btnStart.Size = new System.Drawing.Size(220, 38);
			btnStart.TabIndex = 2;
			btnStart.Text = "다음 문제 넘어가기";
			btnStart.UseVisualStyleBackColor = true;
			btnStart.Click += new System.EventHandler(this.btnStart_Click);
			btnStart.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
			btnStart.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;

			// TextBox 속성: Location, Name, Size, TabIndex
			txtPlus.Location = new System.Drawing.Point(447, 200);
			txtPlus.Name = "txtPlus";
			txtPlus.Size = new System.Drawing.Size(130, 20);
			txtPlus.TabIndex = 29;
			txtPlus.ImeMode = ImeMode.Disable;

			txtMinus.Location = new System.Drawing.Point(447, 240);
			txtMinus.Name = "txtMinus";
			txtMinus.Size = new System.Drawing.Size(130, 20);
			txtMinus.TabIndex = 30;
			txtMinus.ImeMode = ImeMode.Disable;

			txtMulti.Location = new System.Drawing.Point(447, 280);
			txtMulti.Name = "txtMulti";
			txtMulti.Size = new System.Drawing.Size(130, 20);
			txtMulti.TabIndex = 31;
			txtMulti.ImeMode = ImeMode.Disable;

			txtDivide.Location = new System.Drawing.Point(447, 320);
			txtDivide.Name = "txtDivide";
			txtDivide.Size = new System.Drawing.Size(130, 20);
			txtDivide.TabIndex = 32;
			txtDivide.ImeMode = ImeMode.Disable;

			// MainPanel에 게임 프로그램 가져오기 (패널 추가)
			form.pnlMain.Controls.Add(btnStart);
			form.pnlMain.Controls.Add(lblResult);
			form.pnlMain.Controls.Add(lblNotice);

			form.pnlMain.Controls.Add(plusLeftLabel);
			form.pnlMain.Controls.Add(plusLabel);
			form.pnlMain.Controls.Add(plusRightLabel);
			form.pnlMain.Controls.Add(lblEqual1);

			form.pnlMain.Controls.Add(minusLeftLabel);
			form.pnlMain.Controls.Add(minusLabel);
			form.pnlMain.Controls.Add(minusRightLabel);
			form.pnlMain.Controls.Add(lblEqual2);

			form.pnlMain.Controls.Add(multiLeftLabel);
			form.pnlMain.Controls.Add(multiLabel);
			form.pnlMain.Controls.Add(multiRightLabel);
			form.pnlMain.Controls.Add(lblEqual3);

			form.pnlMain.Controls.Add(divLeftLabel);
			form.pnlMain.Controls.Add(divLabel);
			form.pnlMain.Controls.Add(divRightLabel);
			form.pnlMain.Controls.Add(lblEqual4);

			form.pnlMain.Controls.Add(txtPlus);
			form.pnlMain.Controls.Add(txtMinus);
			form.pnlMain.Controls.Add(txtMulti);
			form.pnlMain.Controls.Add(txtDivide);

			StartTheQuiz();
			btnStart.Enabled = true;
		}

		private void StartTheQuiz()
		{
			plus1 = rand.Next(1, 10);
			plus2 = rand.Next(1, 10);
			plusLeftLabel.Text = plus1.ToString();
			plusRightLabel.Text = plus2.ToString();

			minus1 = rand.Next(1, 10);
			minus2 = rand.Next(1, 10);
			minusLeftLabel.Text = minus1.ToString();
			minusRightLabel.Text = minus2.ToString();

			multi1 = rand.Next(1, 10);
			multi2 = rand.Next(1, 10);
			multiLeftLabel.Text = multi1.ToString();
			multiRightLabel.Text = multi2.ToString();

			div1 = rand.Next(1, 10);
			div2 = rand.Next(1, 10);
			divLeftLabel.Text = div1.ToString();
			divRightLabel.Text = div2.ToString();
		}

		private void CheckTheAnswer()
		{
			if (String.IsNullOrWhiteSpace(txtPlus.Text)
				&& String.IsNullOrWhiteSpace(txtMinus.Text)
				&& String.IsNullOrWhiteSpace(txtMulti.Text)
				&& String.IsNullOrWhiteSpace(txtDivide.Text))
			{
				lblResult.Text = "TextBox에 값을 입력해주세요!!";
			}
			else
			{
				try
				{
					if ((plus1 + plus2 == int.Parse(txtPlus.Text))
						&& (minus1 - minus2 == int.Parse(txtMinus.Text))
						&& (multi1 * multi2 == int.Parse(txtMulti.Text))
						&& (div1 / div2 == int.Parse(txtDivide.Text)))
					{
						form.pnlMain.Controls.Clear();
						form.pnlMain_Add();
						form.Visible_Game_Start();
						form.Next_Game();
					}
					else
					{
						lblResult.Text = "틀린 문제가 있습니다. 다시 푸세요.";

						countWrong--; // 오타 기회 횟수
						if (countWrong == 0)
						{
							// 종료구간
							this.ptbHeart1.BackgroundImage = Properties.Resources.hart;
							this.ptbHeart2.BackgroundImage = Properties.Resources.hart;
							this.ptbHeart3.BackgroundImage = Properties.Resources.hart_BG;
						}
					}
				}
				catch (Exception) {
					lblResult.Text = "숫자로만 입력 가능합니다!";
				}
				
			}
		}

		int correctCount = 0; // 정답 맞춘 횟수
		int countWrong = 3; // 오타 기회 횟수	
		public int CorrectWrong = 3; //넘어가기 기능 카운트

		private void btnStart_Click(object sender, EventArgs e)
		{
			CheckTheAnswer();
		}

		// txtPlus, txtMinus, txtMulti, txtDivide 등의 KeyPress 함수
		private void txtPlus_KeyPress(object sender, KeyPressEventArgs e)
		{	//숫자만 입력되도록 필터링
			if (!(char.IsDigit(e.KeyChar) || e.KeyChar == Convert.ToChar(Keys.Back)))
			{ //숫자와 백스페이스를 제외한 나머지를 바로 처리
				e.Handled = true;
			}
		}

		private void txtMinus_KeyPress(object sender, KeyPressEventArgs e)
		{   //숫자만 입력되도록 필터링
			if (!(char.IsDigit(e.KeyChar) || e.KeyChar == Convert.ToChar(Keys.Back)))
			{ //숫자와 백스페이스를 제외한 나머지를 바로 처리
				e.Handled = true;
			}
		}

		private void txtMulti_KeyPress(object sender, KeyPressEventArgs e)
		{   //숫자만 입력되도록 필터링
			if (!(char.IsDigit(e.KeyChar) || e.KeyChar == Convert.ToChar(Keys.Back)))
			{ //숫자와 백스페이스를 제외한 나머지를 바로 처리
				e.Handled = true;
			}
		}

		private void txtDivide_KeyPress(object sender, KeyPressEventArgs e)
		{   //숫자만 입력되도록 필터링
			if (!(char.IsDigit(e.KeyChar) || e.KeyChar == Convert.ToChar(Keys.Back)))
			{ //숫자와 백스페이스를 제외한 나머지를 바로 처리
				e.Handled = true;
			}
		}
	}
}

<GameK002.cs 파일>
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Threading;
using System.Windows.Forms;
using System.Media;
using System.Windows.Media;//참조 추가에서 PresentationCore.dll 추가해야함.

namespace SockSockGame
{// 1번째 게임 프로젝트 만들기
	class GameK002
	{
		//Form1의 요소들에 접근하기 위해 객체 생성
		static Form1 form = Application.OpenForms.OfType<Form1>().FirstOrDefault();

		//랜덤번호 뽑기 위한 랜덤객체
		static Random rnd = new Random();
		private int answer;

		Label label1 = new Label();
		TextBox txtInput = new TextBox();
		Button btnGo = new Button();
		Label lblResult = new Label();

		PictureBox ptbHeart1 = new PictureBox();
		PictureBox ptbHeart2 = new PictureBox();
		PictureBox ptbHeart3 = new PictureBox();

		internal void InitGameK002()
		{// 배경, 텍스트박스, 버튼 세팅
			form.Visible_Game_Start();
			form.pnlMain.BackgroundImage = Properties.Resources.HanRiver_01;//배경화면

			// label1      
			label1.AutoSize = true;
			label1.Font = new System.Drawing.Font("돋움체", 16F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
			label1.Location = new System.Drawing.Point(250, 200);
			label1.Name = "label1";
			label1.Size = new System.Drawing.Size(220, 20);
			label1.TabIndex = 0;
			label1.Text = "Select Between 1~10";
			label1.ForeColor = System.Drawing.Color.White;
			label1.BackColor = System.Drawing.Color.Transparent;
			form.pnlMain.Controls.Add(label1);

			// txtInput          
			txtInput.Location = new System.Drawing.Point(390, 240);
			txtInput.Name = "textBox1";
			txtInput.Size = new System.Drawing.Size(200, 20);
			txtInput.TabIndex = 1;
			txtInput.ImeMode = ImeMode.Disable;
			form.pnlMain.Controls.Add(txtInput);

			// btnGo          
			btnGo.Location = new System.Drawing.Point(415, 270);
			btnGo.Name = "btnGo";
			btnGo.Size = new System.Drawing.Size(150, 30);
			btnGo.TabIndex = 2;
			btnGo.Text = "Go!";
			btnGo.UseVisualStyleBackColor = true;
			btnGo.Click += new System.EventHandler(this.btnGo_Click);
			form.pnlMain.Controls.Add(btnGo);

			// lblResult            
			lblResult.AutoSize = true;
			lblResult.Font = new System.Drawing.Font("굴림", 20F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
			lblResult.Location = new System.Drawing.Point(250, 320);
			lblResult.Name = "lblResult";
			lblResult.Size = new System.Drawing.Size(300, 50);
			lblResult.TabIndex = 4;
			lblResult.Text = " ";
			lblResult.ForeColor = System.Drawing.Color.White;
			lblResult.BackColor = System.Drawing.Color.Transparent;
			form.pnlMain.Controls.Add(lblResult);

			answer = rnd.Next(1, 10);
			label1.Text = "1부터 10까지의 수들 중 가장 알맞은 숫자를 고르세요.";
			lblResult.Text = "숫자 맞추기 게임!";
		}

		int correctCount = 0; // 정답 맞춘 횟수
		int countWrong = 3; // 오타 기회 횟수	
		public int CorrectWrong = 3; //넘어가기 기능 카운트(버튼)

		private void txtInput_KeyPress(object sender, KeyPressEventArgs e)
		{//숫자만 입력되도록 필터링
			if (!(char.IsDigit(e.KeyChar) || e.KeyChar == Convert.ToChar(Keys.Back) || e.KeyChar == 46))
			{   //숫자와 백스페이스, 마침표를 제외한 나머지를 바로 처리
				e.Handled = true;
			}
		}

		private void btnGo_Click(object sender, EventArgs e)
		{
			if (String.IsNullOrWhiteSpace(txtInput.Text))
			{
				lblResult.Text = "TextBox에 값을 입력해주세요!!";
			}
			else
			{
				try
				{
					int NumInput = int.Parse(txtInput.Text);
					if (NumInput < answer)
					{
						lblResult.Text = "더 높습니다.";
					}
					else if (NumInput > answer)
					{
						lblResult.Text = "더 낮습니다.";
					}
					else
					{
						answer = rnd.Next(1, 11);
						form.pnlMain.Controls.Clear();
						form.pnlMain_Add(); // 원래의 컨트롤을 다시 불러올 때 사용
						form.Visible_Game_Start(); // 화면 보일 때 사용
						form.Next_Game();
					}
				}
				catch (Exception) 
				{
					lblResult.Text = "숫자로만 입력 가능합니다!";
				}		
			}
		}
	}
}

**Comment by Hellokjw** [comment]
혹시 모르니까 다시 올리겠습니다.

<GameK001의 문제를 해결한 코드들>
			if (String.IsNullOrWhiteSpace(txtPlus.Text)
			&& String.IsNullOrWhiteSpace(txtMinus.Text)
			&& String.IsNullOrWhiteSpace(txtMulti.Text)
			&& String.IsNullOrWhiteSpace(txtDivide.Text))
			{
				lblResult.Text = "TextBox에 값을 입력해주세요!!";
			}
			else
			{
				try
				{
					if ((plus1 + plus2 == int.Parse(txtPlus.Text))
						&& (minus1 - minus2 == int.Parse(txtMinus.Text))
						&& (multi1 * multi2 == int.Parse(txtMulti.Text))
						&& (div1 / div2 == int.Parse(txtDivide.Text)))
					{
						form.pnlMain.Controls.Clear();
						form.pnlMain_Add();
						form.Visible_Game_Start();
						form.Next_Game();
					}
					else
					{
						lblResult.Text = "틀린 문제가 있습니다. 다시 푸세요.";

						countWrong--; // 오타 기회 횟수
						if (countWrong == 0)
						{
							// 종료구간
							this.ptbHeart1.BackgroundImage = Properties.Resources.hart;
							this.ptbHeart2.BackgroundImage = Properties.Resources.hart;
							this.ptbHeart3.BackgroundImage = Properties.Resources.hart_BG;
						}
					}
				}
				catch (Exception) {
					lblResult.Text = "숫자로만 입력 가능합니다!";
				}
			}

- 문제의 원인: 처음에는 정답 판별 조건문만 작성했는데, 실행 중에 예외가 발생해서 텍스트박스 문자에 대한 오류가 발생했습니다.
- 해결 방법: 그런데 try~catch 문을 사용해서 조건문을 예외 처리 해주었더니 오류가 발생하지 않았습니다.


<GameK002의 문제를 해결한 코드들>
private void btnGo_Click(object sender, EventArgs e)
{
		if (String.IsNullOrWhiteSpace(txtInput.Text))
		{
			lblResult.Text = "TextBox에 값을 입력해주세요!!";
		}
		else
		{
			try
			{
				int NumInput = int.Parse(txtInput.Text);
				if (NumInput < answer)
				{
					lblResult.Text = "더 높습니다.";
				}
				else if (NumInput > answer)
				{
					lblResult.Text = "더 낮습니다.";
				}
				else
				{
					answer = rnd.Next(1, 11);
					form.pnlMain.Controls.Clear();
					form.pnlMain_Add(); // 원래의 컨트롤을 다시 불러올 때 사용
					form.Visible_Game_Start(); // 화면 보일 때 사용
					form.Next_Game();
				}
			}
			catch (Exception) 
			{
				lblResult.Text = "숫자로만 입력 가능합니다!";
			}		
		}
}

- 문제의 원인: 처음에는 "int NumInput = int.Parse(txtInput.Text);" 처럼 NumInput 변수에 대한 선언만 했기 때문에 예외가 발생해서 텍스트박스 문자에 대한 오류가 발생했습니다.
- 해결 방법: 그런데 try~catch 문을 사용해서 예외 처리를 했더니 오류가 발생하지 않았습니다.

**Comment by Hellokjw** [comment]
혹시나 이해가 안 되실까봐 다시 올리겠습니다.

<GameK001의 문제를 해결한 코드들>
			if (String.IsNullOrWhiteSpace(txtPlus.Text)
			&& String.IsNullOrWhiteSpace(txtMinus.Text)
			&& String.IsNullOrWhiteSpace(txtMulti.Text)
			&& String.IsNullOrWhiteSpace(txtDivide.Text))
			{
				lblResult.Text = "TextBox에 값을 입력해주세요!!";
			}
			else
			{
				try
				{
					if ((plus1 + plus2 == int.Parse(txtPlus.Text))
						&& (minus1 - minus2 == int.Parse(txtMinus.Text))
						&& (multi1 * multi2 == int.Parse(txtMulti.Text))
						&& (div1 / div2 == int.Parse(txtDivide.Text)))
					{
						form.pnlMain.Controls.Clear();
						form.pnlMain_Add();
						form.Visible_Game_Start();
						form.Next_Game();
					}
					else
					{
						lblResult.Text = "틀린 문제가 있습니다. 다시 푸세요.";

						countWrong--; // 오타 기회 횟수
						if (countWrong == 0)
						{
							// 종료구간
							this.ptbHeart1.BackgroundImage = Properties.Resources.hart;
							this.ptbHeart2.BackgroundImage = Properties.Resources.hart;
							this.ptbHeart3.BackgroundImage = Properties.Resources.hart_BG;
						}
					}
				}
				catch (Exception) {
					lblResult.Text = "숫자로만 입력 가능합니다!";
				}
			}

- 문제의 원인: 처음에는 정답 판별 조건문만 작성했는데, 실행 중에 예외가 발생해서 텍스트박스 문자에 대한 오류가 발생했습니다.
- 해결 방법: 그런데 try~catch 문을 사용해서 조건문을 예외 처리 해주었더니 오류가 발생하지 않았습니다.


<GameK002의 문제를 해결한 코드들>
private void btnGo_Click(object sender, EventArgs e)
{
		if (String.IsNullOrWhiteSpace(txtInput.Text))
		{
			lblResult.Text = "TextBox에 값을 입력해주세요!!";
		}
		else
		{
			try
			{
				int NumInput = int.Parse(txtInput.Text);
				if (NumInput < answer)
				{
					lblResult.Text = "더 높습니다.";
				}
				else if (NumInput > answer)
				{
					lblResult.Text = "더 낮습니다.";
				}
				else
				{
					answer = rnd.Next(1, 11);
					form.pnlMain.Controls.Clear();
					form.pnlMain_Add(); // 원래의 컨트롤을 다시 불러올 때 사용
					form.Visible_Game_Start(); // 화면 보일 때 사용
					form.Next_Game();
				}
			}
			catch (Exception) 
			{
				lblResult.Text = "숫자로만 입력 가능합니다!";
			}		
		}
}

- 문제의 원인: 처음에는 "int NumInput = int.Parse(txtInput.Text);" 처럼 NumInput 변수에 대한 선언만 했기 때문에 예외가 발생해서 텍스트박스 문자에 대한 오류가 발생했습니다.
- 해결 방법: 그런데 try~catch 문을 사용해서 예외 처리를 했더니 오류가 발생하지 않았습니다.

**Comment by Hellokjw** [comment]
혹시 모르니까 다시 올리겠습니다.

<GameK001의 문제를 해결한 코드들>
			if (String.IsNullOrWhiteSpace(txtPlus.Text)
			&& String.IsNullOrWhiteSpace(txtMinus.Text)
			&& String.IsNullOrWhiteSpace(txtMulti.Text)
			&& String.IsNullOrWhiteSpace(txtDivide.Text))
			{
				lblResult.Text = "TextBox에 값을 입력해주세요!!";
			}
			else
			{
				try
				{
					if ((plus1 + plus2 == int.Parse(txtPlus.Text))
						&& (minus1 - minus2 == int.Parse(txtMinus.Text))
						&& (multi1 * multi2 == int.Parse(txtMulti.Text))
						&& (div1 / div2 == int.Parse(txtDivide.Text)))
					{
						form.pnlMain.Controls.Clear();
						form.pnlMain_Add();
						form.Visible_Game_Start();
						form.Next_Game();
					}
					else
					{
						lblResult.Text = "틀린 문제가 있습니다. 다시 푸세요.";

						countWrong--; // 오타 기회 횟수
						if (countWrong == 0)
						{
							// 종료구간
							this.ptbHeart1.BackgroundImage = Properties.Resources.hart;
							this.ptbHeart2.BackgroundImage = Properties.Resources.hart;
							this.ptbHeart3.BackgroundImage = Properties.Resources.hart_BG;
						}
					}
				}
				catch (Exception) {
					lblResult.Text = "숫자로만 입력 가능합니다!";
				}
			}

- 문제의 원인: 처음에는 정답 판별 조건문만 작성했는데, 실행 중에 예외가 발생해서 텍스트박스 문자에 대한 오류가 발생했습니다.
- 해결 방법: 그런데 try~catch 문을 사용해서 조건문을 예외 처리 해주었더니 오류가 발생하지 않았습니다.


<GameK002의 문제를 해결한 코드들>
private void btnGo_Click(object sender, EventArgs e)
{
		if (String.IsNullOrWhiteSpace(txtInput.Text))
		{
			lblResult.Text = "TextBox에 값을 입력해주세요!!";
		}
		else
		{
			try
			{
				int NumInput = int.Parse(txtInput.Text);
				if (NumInput < answer)
				{
					lblResult.Text = "더 높습니다.";
				}
				else if (NumInput > answer)
				{
					lblResult.Text = "더 낮습니다.";
				}
				else
				{
					answer = rnd.Next(1, 11);
					form.pnlMain.Controls.Clear();
					form.pnlMain_Add(); // 원래의 컨트롤을 다시 불러올 때 사용
					form.Visible_Game_Start(); // 화면 보일 때 사용
					form.Next_Game();
				}
			}
			catch (Exception) 
			{
				lblResult.Text = "숫자로만 입력 가능합니다!";
			}		
		}
}

- 문제의 원인: 처음에는 "int NumInput = int.Parse(txtInput.Text);" 처럼 NumInput 변수에 대한 선언만 했기 때문에 예외가 발생해서 텍스트박스 문자에 대한 오류가 발생했습니다.
- 해결 방법: 그런데 try~catch 문을 사용해서 예외 처리를 했더니 오류가 발생하지 않았습니다.
