### ISSUE TITLE
[버그]GameS001 같은 단어가 나왔을 경우 하나 지워지고 나서 나머지들 안지워짐

### ISSUE THREAD

**Issue by alswodl23** [alswodl23/Project#15]
같은 글자 안나오도록 처리해야할듯.

**Comment by sylviethebest** [comment]
// 인덱스 중복 없이 랜덤으로 생성하는 리스트
            List<int> ranIdx = new List<int>();
            int iSelect;
            for(int i = 0; i < 5; i++)
            {
                do
                {
                    iSelect = new Random().Next(word.Length);
                }
                while (ranIdx.Contains(iSelect));
                ranIdx.Add(iSelect);
            }
