### ISSUE TITLE
[버그]GameS003 다음 게임으로 안넘어감

### ISSUE THREAD

**Issue by alswodl23** [alswodl23/Project#16]
다음 게임 넘어가기 전에 UI 제거 작업 부탁드려요.

**Comment by sylviethebest** [comment]
if (field[x, y] == -1)
            {
                b.Text = "X";
                MessageBox.Show("폭탄을 찾았습니다!");
                finishGame();
            }
        internal void finishGame()
        {
            form.pnlMain.Controls.Clear();
            form.pnlMain_Add();
            form.Visible_Game_Start();
            form.Next_Game();
        }

**Comment by sylviethebest** [comment]
internal void finishGame()
        {
            form.pnlMain.Controls.Clear();
            form.pnlMain_Add();
            form.Visible_Game_Start();
            form.Next_Game();
        }
