### ISSUE TITLE
[버그] S003 인데스가 배열 범위를 벗어났습니다.

### ISSUE THREAD

**Issue by alswodl23** [alswodl23/Project#17]
95번째줄 
if (field[x, y] == -1)
System.IndexOutOfRangeException: '인덱스가 배열 범위를 벗어났습니다.'

**Comment by sylviethebest** [comment]
internal void setGame()
        {
            init(7, 7, 5);
            for (int x = 0; x < field.GetLength(0); x++)
            {
                for (int y = 0; y < field.GetLength(1); y++)
                {
                    Button b = new Button();
                    buttons[x, y] = b;
                    b.Font = new Font("Arial", 40);
                    b.Left = (x * 80) + 240;
                    b.Top = (y * 80) + 160;
                    b.Width = 80;
                    b.Height = 80;
                    b.Text = "";
                    form.pnlMain.Controls.Add(b);
                    b.Click += B_Click;
                }
            }

        }
        internal void B_Click(object sender, EventArgs e)
        {
            Button b = (Button)sender;
            int x = (b.Left - 240) / 80;
            int y = (b.Top - 160) / 80;
            if (field[x, y] == -1)
            {
                b.Text = "X";
                MessageBox.Show("폭탄을 찾았습니다!");
                finishGame();
            }
            else
            {
                if (field[x, y] == 0)
                {
                    b.Text = "";
                    lala(x, y);
                }
                else
                {
                    b.Text = "" + field[x, y];
                }
                b.Enabled = false;
            }
        }
