### ISSUE TITLE
[버그] 두더지 안잡기 시 다시시작해도 쓰레드 지속

### ISSUE THREAD

**Issue by janetchu05** [alswodl23/Project#20]
두더지 안 잡기 게임 플레이 -> 다시시작버튼 -> 스레드 살아있어서 게임 두개가 출력

**Comment by alswodl23** [comment]
412줄
        public void btnHome_Click(object sender, EventArgs e)
        {
            if (thrOn == true)
            {
                thrOn = false;
                thrG.Abort();
            }

474줄
        private void btnReStart_Click(object sender, EventArgs e)
        {
            if (thrOn == true)
            {
                thrOn = false;
                thrG.Abort();
            }
