### ISSUE TITLE
[버그] 다시시작시 기존 난이도, 무한모드 리셋

### ISSUE THREAD

**Issue by janetchu05** [alswodl23/Project#22]
게임 실행 중 -> 다시시작 버튼 클릭 -> 난이도 하/무한모드 해제로 변경됨(기존 선택 난이도/무한모드여부 저장 필요)

**Comment by alswodl23** [comment]
private void btnReStart_Click(object sender, EventArgs e)
        {
            int rbTemp = 0;
            int chbTemp = 0;

            if (thrOn == true)
            {
                thrOn = false;
                thrG.Abort();
            }

            if (cbUnlimit.Checked == true)
            {
                chbTemp = 1;
            }

            if (rbtEasy.Checked == true)
            {
                rbTemp = 0;
            }
            else if (rbtNormal.Checked == true)
            {
                rbTemp = 1;
            }
            else if (rbtHard.Checked == true)
            {
                rbTemp = 2;
            }

            timer.Stop();
            this.Controls.Clear();
            this.InitializeComponent();

            if (chbTemp == 1)
            {
                cbUnlimit.Checked = true;
            }

            if (rbTemp == 0)
            {
                rbtNormal.Checked = true;
            }
            else if (rbTemp == 1)
            {
                rbtEasy.Checked = true;
            }
            else if (rbTemp == 2)
            {
                rbtHard.Checked = true;
            }

            txtID.Text = id;
            skipGame = 3;
            this.btnStart.PerformClick();
        }
