### ISSUE TITLE
[버그] 카드게임 더블클릭 시 그냥 뒤집혀버림

### ISSUE THREAD

**Issue by janetchu05** [alswodl23/Project#23]
카드게임 실행 중 -> 두개의 같은 카드가 아니라 더블클릭 -> 그냥 뒤집힘

**Comment by alswodl23** [comment]
L003 21줄
private void btnCard_Click(object sender, EventArgs e)
{
.
.
.
            buffer.Enabled = false;

            if (card == 2)
            {
                btnPrev.Enabled = true;
                buffer.Enabled = true;
