### ISSUE TITLE
[버그] 처음으로 / 다시시작 버튼 클릭시 생명 초기화 안됨

### ISSUE THREAD

**Issue by janetchu05** [alswodl23/Project#7]
폼 로드 후 게임 진행하다가 처음으로 or 다시시작 버튼 클릭 - 정상적으로 게임 처음부터 진행은 되지만넘어가기 버튼 무한으로 선택 가능해지고 생명 사라지지 않음...

**Comment by jamsuham75** [comment]
Assignees 지정 안하셨네요. 지정자 할당 해주세요.

**Comment by janetchu05** [comment]
btnRestart_Click 과 btnHome_Click 이벤트 핸들러에서 SkipGame = 3으로 초기화 해주면 해결가능


        public void btnHome_Click(object sender, EventArgs e)
        {
            timer.Stop();
            skipGame = 3;  //이부분 추가
            this.Controls.Clear();
            this.InitializeComponent();
        }

        private void btnReStart_Click(object sender, EventArgs e)
        {
            timer.Stop();
            this.Controls.Clear();
            this.InitializeComponent();
            txtID.Text = id;
            skipGame = 3;  //이부분 추가
            this.btnStart.PerformClick();
        }
