### ISSUE TITLE
[버그]GameK003 텍스트 박스 줄넘기기 이슈

### ISSUE THREAD

**Issue by alswodl23** [alswodl23/Project#9]
K003게임 한 줄 문장 작성하는 게임인데 엔터를 치면 줄 바꾸기가 됨.

**Comment by Hellokjw** [comment]
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Threading;
using System.Windows.Forms;

namespace SockSockGame
{
	class GameK003
	{
		//Form1의 요소들에 접근하기 위해 객체 생성
		static Form1 form = Application.OpenForms.OfType<Form1>().FirstOrDefault();

		//랜덤번호 뽑기 위한 랜덤객체
		Random rand = new Random();

		// 문장 배열
		string[] sentence = {
			"인간의 죽음은 패배했을 때가 아니라 포기했을 때에 온다.",
			"신은 어딘가 하늘 아래 그대만이 할 수 있는 일을 마련해 놓았다.",
			"위대한 업적을 이룬 것은 힘이 아니라 불굴의 노력이다.",
			"실패란 성공이란 진로를 알려주는 나침반이다.",
			"제 갈 길을 아는 사람에게 세상은 길을 비켜준다.",
			"인간은 재주가 없어서라기보다는 목적이 없어서 실패한다.",
			"겁장이는 천 번을 죽지만, 사나이는 한 번만 죽는다.",
			"교육의 목적은 '일생을 통하여 공부하는 자세를 갖게 하는 것'이다.",
			"하느님을 변화시키기 위해서가 아니라, 자신을 변화시키기 위해서 기도를 한다.",
			"제일 어려운 수학 문제는 우리가 신이나 이웃에게 받은 축복을 세어 보는 것이다."
		};

		// 폼 구현을 위한 객체 생성
		Label lblSentence = new Label();
		TextBox txtInput = new TextBox();
		Button btnNext = new Button();
		Label lblNotice = new Label();

		internal void InitGameK003()
		{ // 배경, 라벨, 텍스트박스, 버튼, 리스트박스 세팅
			form.Visible_Game_Start();
			form.pnlMain.BackgroundImage = Properties.Resources.HanRiver;//배경화면
			setGame();

			// txtInput
			txtInput.Font = new System.Drawing.Font("굴림", 14F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
			txtInput.Location = new System.Drawing.Point(120, 180);
			txtInput.Name = "txtInput";
			txtInput.Size = new System.Drawing.Size(758, 30);
			txtInput.Multiline = true;
			txtInput.TabIndex = 1;

			// btnNext
			btnNext.Location = new System.Drawing.Point(120, 260);
			btnNext.Name = "btnNext";
			btnNext.Size = new System.Drawing.Size(114, 30);
			btnNext.TabIndex = 2;
			btnNext.Text = "다음 문장";
			btnNext.UseVisualStyleBackColor = true;
			btnNext.Click += new System.EventHandler(this.btnNext_Click);

			// lblNotice
			lblNotice.AutoSize = true;
			lblNotice.Font = new System.Drawing.Font("굴림", 30.5F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
			lblNotice.Location = new System.Drawing.Point(120, 301);
			lblNotice.Name = "lblNotice";
			lblNotice.Size = new System.Drawing.Size(0, 22);
			lblNotice.TabIndex = 3;
			lblNotice.Text = " ";
			lblNotice.ForeColor = System.Drawing.Color.White;
			lblNotice.BackColor = System.Drawing.Color.Transparent;

			form.pnlMain.Controls.Add(txtInput);
			form.pnlMain.Controls.Add(btnNext);
			form.pnlMain.Controls.Add(lblNotice);
		}

		internal void setGame()
		{
			// 문장 리스트 인덱스 랜덤 넘버링
			int SentenceRan = rand.Next(sentence.Length);

			// 문장 배치
			int[] wordX = new int[10];

			// 랜덤 문장를 화면에 출력
			showSentence(lblSentence, SentenceRan);
		}

		// 문장 레이블 속성(표시 부분)
		internal void showSentence(Label lblSentence, int num)
		{
			lblSentence.AutoSize = true;
			lblSentence.Font = new System.Drawing.Font("돋움체", 15F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
			lblSentence.Location = new System.Drawing.Point(110, 150);
			lblSentence.Name = "label1";
			lblSentence.Size = new System.Drawing.Size(0, 20);
			lblSentence.TabIndex = 0;
			lblSentence.Text = sentence[num].ToString();

			lblSentence.ForeColor = System.Drawing.Color.White;
			lblSentence.BackColor = System.Drawing.Color.Transparent;
			form.pnlMain.Controls.Add(lblSentence);
		}

		private void btnNext_Click(object sender, EventArgs e)
		{
			if (lblSentence.Text == txtInput.Text)
			{
				// 종료 구간
				lblNotice.Text = "정답입니다. 다음 단계로 넘어갑니다.";
				form.pnlMain.Controls.Clear();
				form.pnlMain_Add(); // 원래의 컨트롤을 다시 불러올 때 사용
				form.Visible_Game_Start(); // 화면 보일 때 사용
				form.Next_Game();
			}
			else
			{
				lblNotice.Text = "오타가 있습니다. 다시 입력하세요.";
				correctSentence();
			}
		}

		internal void initTextbox()
		{
			txtInput.Text = "";
		}

		// 엔터키 눌렀을 때 입력 가능
		internal void txtInput_KeyDown(object sender, KeyEventArgs e)
		{
			string keyword = txtInput.Text; 
			char[] except = {'\n'};
			keyword = keyword.Trim(except);

			if (e.KeyCode == Keys.Enter)
			{
				btnEnter_Click(sender, e);
				initTextbox();
			}
		}

		// 화면에 띄워진 문장과 입력한 문장이 같을때 띄워진 문장이 사라짐, 오타 3번 입력 시 게임 자동 종료
		internal void btnEnter_Click(object sender, EventArgs e)
		{
			this.ptbHeart1.BackgroundImage = Properties.Resources.hart;
			this.ptbHeart2.BackgroundImage = Properties.Resources.hart;
			this.ptbHeart3.BackgroundImage = Properties.Resources.hart;

			correctSentence();
		}

		int correctCount = 0; // 정답 맞춘 횟수
		int countWrong = 3; // 오타 기회 횟수

		//넘어가기 기능 카운트(버튼 누른 횟수)
		public int correctWrong = 3;

		//스레드
		public bool thrOn = false;

		PictureBox ptbHeart1 = new PictureBox();
		PictureBox ptbHeart2 = new PictureBox();
		PictureBox ptbHeart3 = new PictureBox();

		internal void correctSentence()
		{
			if (txtInput.Text == lblSentence.Text)
			{
				form.pnlMain.Controls.Remove(lblSentence);
				correctCount++;
			}
			else
			{
				countWrong--; // 오타 기회 횟수
				if (countWrong == 0)
				{
					// 종료구간
					this.ptbHeart1.BackgroundImage = Properties.Resources.hart_BG;

					form.pnlMain.Controls.Clear();
					form.pnlMain_Add(); // 원래의 컨트롤을 다시 불러올 때 사용
					form.Visible_Game_Start(); // 화면 보일 때 사용
					form.Next_Game();
				}
			}
		}
	}
}

// GameK003 텍스트 박스 줄넘기기 이슈
// K003게임 한 줄 문장 작성하는 게임인데 엔터를 치면 줄 바꾸기가 됨.
